generator_prompt ="""You are a helpful agent tasked with solving some financial problems. Solve the given question by having a Thought, then Finish with your answer. Thought provides a step-by-step reasoning trace needed to think and solve the problem. You should place your answer within square brackets after the prefix "Finish". So let's say your final answer is "apple", you should present the answer as Final[apple]. This will finish the task. You are also given context that you should use to help answer the question. In addition to this, you are given a cheatsheet that provides you with relevant strategies, insights and common pitfalls encountered while answering financial questions. You can make use of this cheatsheet to answer the question. 

## CHEATSHEET

{}

-----
-----

## REFLECTION 

{}

-----
-----

## CONTEXT

{}

—--
—--

Now it is time to solve the following question.

## QUESTION

{}

"""


reflector_prompt="""You are an advanced reasoning agent that can improve based on self reflection. You will be given a previous reasoning trial you produced in addition to the relevant context and a question. You are also given the final answer you gave along with the actual ground truth answer. The ground truth answer is not wrong, so you should not assume that there is any discrepancy in the ground truth answer. You were unsuccessful in answering the question as your answer differs from the ground truth. This is either because you gave the wrong answer with Finish[<answer>] or there was a phrasing discrepancy with your provided answer and the answer key. In a few sentences, diagnose a possible reason for failure or phrasing discrepancy and devise a new, concise, high level plan that aims to mitigate this failure. Following is all the information you will need for this. 


REASONING TRIAL 

{}

—--
—--


QUESTION

{}

—--
—--


CONTEXT 

{}

—--
—--


FINAL ANSWER 

{}

—--
—--


GROUND TRUTH ANSWER 

{}

"""

curator_prompt = """
You are an advanced reasoning agent that curates cheatsheets for LLMs to help them solve financial tasks. You will be given a previous reasoning trial, and previous cheatsheet that you produced in addition to the current question and its response generated by another LLM. Your job is to use the previous cheatsheet and the response given to you to curate a new cheatsheet. You should think about extracting the most relevant insights, strategies, methodologies, common mistakes and anything else that you might think would be helpful for the LLM to solve future problems. You are allowed to append these new insights to the previous cheatsheet. You can also remove redundant or repeated information from the previous cheatsheet, but keep in mind that the information removed would be lost permanently. Enclose the cheatsheet in <cheatsheet> and </cheatsheet> tags, to help with cheatsheet extraction. Following is all the information you will need for this. 
PREVIOUS REASONING

{}

-----
-----


PREVIOUS CHEATSHEET

{}

-----
-----


CURRENT INPUT

{}

-----
-----


ANSWER TO THE CURRENT INPUT

{}

"""


'''
curator_prompt="""You are a helpful cheatsheet curator. You are tasked with creating a continuously evolving reference designed to help solve financial data reasoning tasks. You will see a financial question, the related context that was used to answer the question along with the answer produced by the generator LLM. You are also given access to the previous cheatsheet that was used to answer this question. 

Your task is to extract the most useful and relevant solutions and strategies, while preserving the old cheatsheet content. Continuously update and improve the content of the cheatsheet by incorporating new insights and solutions, removing repetitions or trivial information, and adding efficient solutions. Provide clear solutions and meta strategies, avoid trivial content and focus on critical solution details and common pitfalls encountered while solving these problems. 

Below you will find cheatsheet structure and formatting guidelines. 

#### Cheatsheet Structure
The cheatsheet can be divided into the following sections:

1. Solutions, Implementation Patterns, and Code Snippets:
   - Document reusable code snippets, algorithms, and solution templates.
   - Include descriptions, annotated examples, and potential pitfalls, albeit succinctly.

2. [OPTIONAL] Edge Cases and Validation Traps:
   - Catalog scenarios that commonly cause errors or unexpected behavior.
   - Provide checks, validations, or alternative approaches to handle them.

3. [OPTIONAL] General Meta-Reasoning Strategies:
   - Describe high-level problem-solving frameworks and heuristics (e.g., use Python to solve heuristic problems; in bipartite graphs, max matching = min vertex cover, etc.)
   - Provide concrete yet succinct step-by-step guides for tackling complex problems.

4. Implement a Usage Counter
   - Each entry must include a usage count: Increase the count every time a strategy is successfully used in problem-solving.
   - Use the count to prioritize frequently used solutions over rarely applied ones.

---

#### Formatting Guidelines
Use the following structure for each memory item:

```
<memory_item>
<description>
[Briefly describe the problem context, purpose, and key aspects of the solution.] (Refence: Q1, Q2, Q6, etc.)
</description>
<example>
[Provide a well-documented code snippet, worked-out solution, or efficient strategy.]
</example>
</memory_item>
** Count:  [Number of times this strategy has been used to solve a problem.]


<memory_item>
[...]
</memory_item>

[...]

<memory_item>
[...]
</memory_item>

```

- Tagging: Use references like `(Q14)` or `(Q22)` to link entries to their originating contexts.
- Grouping: Organize entries into logical sections and subsections.
- Prioritizing: incorporate efficient algorithmic solutions, tricks, and strategies into the cheatsheet.
- Diversity: Have as many useful and relevant memory items as possible to guide the model to tackle future questions.

N.B. Keep in mind that once the cheatsheet is updated, any previous content not directly included will be lost and cannot be retrieved. Therefore, make sure to explicitly copy any (or all) relevant information from the previous cheatsheet to the new cheatsheet!!!

---

#### Cheatsheet Template
Use the following format for creating and updating the cheatsheet:

NEW CHEATSHEET:
```
<cheatsheet>

Version: [Version Number]

SOLUTIONS, IMPLEMENTATION PATTERNS, AND CODE SNIPPETS
<memory_item>
[...]
</memory_item>

<memory_item>
[...]
</memory_item>

GENERAL META-REASONING STRATEGIES
<memory_item>
[...]
</memory_item>

</cheatsheet>
```

## PREVIOUS CHEATSHEET

{}

-----
-----


## CURRENT INPUT

{}

-----
-----


## EVIDENCE CONTEXT 

{}

-----
-----


## ANSWER TO THE CURRENT INPUT

{}

"""
'''

